# Generated by Django 4.0.3 on 2022-03-16 00:42

import config.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=config.helpers.UploadTo('client/avatar')),
        ),
    ]
