# Generated by Django 4.0.3 on 2022-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('1', 'owner'), ('2', 'user')], default='2', max_length=1, null=True),
        ),
    ]
