# Generated by Django 4.0.3 on 2022-03-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='main.restaurant'),
            preserve_default=False,
        ),
    ]
