# Generated by Django 4.0.3 on 2022-03-11 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='emaail',
            new_name='email',
        ),
    ]
