# Generated by Django 4.0.3 on 2022-03-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mealcategory_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
        migrations.AlterModelOptions(
            name='mealcategory',
            options={'verbose_name': 'meal_category', 'verbose_name_plural': 'meal_categories'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'restaurant', 'verbose_name_plural': 'restaurants'},
        ),
        migrations.AddField(
            model_name='meal',
            name='tag',
            field=models.ManyToManyField(related_name='meal_category', to='main.mealcategory'),
        ),
        migrations.AddField(
            model_name='mealcategory',
            name='tag',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
