# Generated by Django 4.0.3 on 2022-03-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_meal_options_alter_mealcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcategory',
            name='tag',
        ),
    ]
