# Generated by Django 4.0.3 on 2022-03-14 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_restaurantmenu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbook',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='foodbook',
            name='book_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='foodbook',
            name='book_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='foodbook',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='main.restaurantmenu'),
        ),
        migrations.AddField(
            model_name='foodbook',
            name='status',
            field=models.CharField(choices=[('1', 'Done'), ('2', 'Not yet'), ('3', 'Doing')], default='1', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='foodbook',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='clientUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
