# Generated by Django 4.0.3 on 2022-03-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_mealcategory_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='tag',
        ),
    ]
