# Generated by Django 4.0.3 on 2022-03-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='features',
            field=models.CharField(choices=[('B', 'breakfast'), ('L', 'launch'), ('D', 'dinner')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='timing',
            field=models.CharField(choices=[('D', 'duw'), ('D', 'duw'), ('D', 'duw')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
