# Generated by Django 4.0.3 on 2022-03-15 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_seat_tablebook_book_end_tablebook_book_start_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableBook',
            new_name='SeatBook',
        ),
    ]
