# Generated by Django 4.0.3 on 2022-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_features_order_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timing',
            field=models.CharField(choices=[('M', 'monday'), ('T', 'tuesday'), ('W', 'wednesday'), ('T', 'thursday'), ('F', 'friday'), ('S', 'saturday')], max_length=50),
        ),
    ]
