# Generated by Django 4.0.3 on 2022-03-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timing',
            field=models.CharField(choices=[('Sunday', 'sunday'), ('Monday', 'monday'), ('Tuesday', 'tuesday'), ('Wednesday', 'wednesday'), ('Thursday', 'thursday'), ('Friday', 'friday'), ('Saturday', 'saturday')], max_length=50),
        ),
    ]
