# Generated by Django 4.0.3 on 2022-03-18 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_restaurant_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='owner',
            new_name='user',
        ),
    ]
