# Generated by Django 4.0.3 on 2022-03-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_owner_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbook',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
        migrations.AddField(
            model_name='foodbook',
            name='sum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
