# Generated by Django 4.0.3 on 2022-03-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_foodbook_restaurant_foodbook_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbook',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
    ]
