# Generated by Django 4.0.3 on 2022-03-19 22:56

import config.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_seatbook_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=120, null=True)),
                ('name_ru', models.CharField(max_length=120, null=True)),
                ('name_en', models.CharField(max_length=120, null=True)),
                ('icon', models.ImageField(upload_to='', verbose_name=config.helpers.UploadTo('returant/category'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='seat',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='name_uz',
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.seatcategory'),
        ),
    ]
