# Generated by Django 4.0.3 on 2022-04-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_seatcategory_remove_seat_name_en_remove_seat_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbook',
            name='book_end',
        ),
        migrations.RemoveField(
            model_name='foodbook',
            name='book_start',
        ),
    ]
